server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.champsoft: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  application:
    name: Music

  datasource:
    url: jdbc:h2:mem:music-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: pwd
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      platform: mysql
      mode: always