server:
  port: 8080
  error:
    include-message: always
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.champlain: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  application:
    name: playlist-service
  #  config:
  #    activate:
  #      on-profile: default
  datasource:
    url: jdbc:mysql://mysql4/playlist-db
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      platform: mysql
      mode: always
      logging:
        enabled: true

app:
  user-service:
    host: userservicehost
    port: 8080
  song-service:
    host: songservicehost
    port: 8080

---
#for h2
spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:playlist-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop         #let jpa create the schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        auto-quote-keyword: true
    defer-datasource-initialization: true  #turn this on to ensure that hibernate initializes the schema before loading the data

app:
  user-service:
    host: localhost
    port: 8080
  song-service:
    host: localhost
    port: 8080