server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.champlain: TRACE

spring:
  application:
    name: artist-service

---

# Default profile (real MongoDB)
spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      username: user
      password: pwd
      host: localhost
      port: 27017
      database: artist-db
      authentication-database: admin
      auto-index-creation: true

app:
  song-service:
    host: songservicehost
    port: 8080

---

# Test profile (embedded MongoDB)
spring:
  config:
    activate:
      on-profile: test-profile
  data:
    mongodb:
      database: artist-db

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

app:
  song-service:
    host: localhost
    port: 8080